<script setup>
import {
  Ambulance,
  ArrowLeft,
  ArrowLeftRight,
  Ban,
  Bed,
  Bell,
  Building2,
  Calendar,
  Camera,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDollarSign,
  CirclePlay,
  Clock,
  DoorOpen,
  Download,
  Droplet,
  EllipsisVertical,
  Eye,
  EyeOff,
  FileText,
  FlaskConical,
  HeartPulse,
  Hospital,
  House,
  Key,
  Layers,
  LayoutDashboard,
  Lock,
  LogOut,
  Mail,
  Menu,
  Minus,
  Monitor,
  Moon,
  Package,
  PanelLeft,
  Pencil,
  Phone,
  Pill,
  Plus,
  Receipt,
  RefreshCw,
  ScanLine,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  Siren,
  Stethoscope,
  Store,
  Sun,
  Tag,
  Trash2,
  Truck,
  Upload,
  User,
  UserPlus,
  Users,
  Wallet,
  Wrench,
  X,
} from '@lucide/vue'

const props = defineProps({
  name: { type: String, required: true },
  size: { type: [Number, String], default: 18 },
})

const icons = {
  desk: Monitor,
  users: Users,
  stethoscope: Stethoscope,
  emergency: Siren,
  hospital: Hospital,
  bed: Bed,
  cut: Scissors,
  flask: FlaskConical,
  scan: ScanLine,
  pill: Pill,
  transfer: ArrowLeftRight,
  heartbeat: HeartPulse,
  ambulance: Ambulance,
  receipt: Receipt,
  chart: ChartColumn,
  dashboard: LayoutDashboard,
  building: Building2,
  community: House,
  shield: Shield,
  plus: Plus,
  edit: Pencil,
  eye: Eye,
  refresh: RefreshCw,
  menu: Menu,
  logout: LogOut,
  search: Search,
  x: X,
  user: User,
  cross: Plus,
  back: ArrowLeft,
  chevron: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  check: Check,
  calendar: Calendar,
  clock: Clock,
  upload: Upload,
  download: Download,
  minus: Minus,
  lock: Lock,
  key: Key,
  mail: Mail,
  phone: Phone,
  eyeOff: EyeOff,
  bell: Bell,
  settings: Settings,
  box: Package,
  tag: Tag,
  truck: Truck,
  store: Store,
  layers: Layers,
  coin: CircleDollarSign,
  droplet: Droplet,
  camera: Camera,
  panel: PanelLeft,
  server: Server,
  sun: Sun,
  moon: Moon,
  trash: Trash2,
  more: EllipsisVertical,
  ban: Ban,
  send: Send,
  wallet: Wallet,
  wrench: Wrench,
  play: CirclePlay,
  fileText: FileText,
  door: DoorOpen,
  userPlus: UserPlus,
}

const icon = computed(() => icons[props.name] || icons.cross)
const px = computed(() => Number(props.size) || 18)
</script>

<template>
  <component
    :is="icon"
    class="h-icon"
    :size="px"
    :stroke-width="1.8"
    aria-hidden="true"
  />
</template>
