/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FacilityBoard: typeof import('./resources/js/components/hms/FacilityBoard.vue')['default']
    HBadge: typeof import('./resources/js/components/ui/HBadge.vue')['default']
    HButton: typeof import('./resources/js/components/ui/HButton.vue')['default']
    HCard: typeof import('./resources/js/components/ui/HCard.vue')['default']
    HDialog: typeof import('./resources/js/components/ui/HDialog.vue')['default']
    HIcon: typeof import('./resources/js/components/ui/HIcon.vue')['default']
    HInput: typeof import('./resources/js/components/ui/HInput.vue')['default']
    HmsShell: typeof import('./resources/js/layouts/HmsShell.vue')['default']
    HPage: typeof import('./resources/js/components/ui/HPage.vue')['default']
    HSegmented: typeof import('./resources/js/components/ui/HSegmented.vue')['default']
    HSelect: typeof import('./resources/js/components/ui/HSelect.vue')['default']
    HStat: typeof import('./resources/js/components/ui/HStat.vue')['default']
    HTable: typeof import('./resources/js/components/ui/HTable.vue')['default']
    HTextarea: typeof import('./resources/js/components/ui/HTextarea.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
