/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EncounterChart: typeof import('./resources/js/components/hms/EncounterChart.vue')['default']
    FacilityBoard: typeof import('./resources/js/components/hms/FacilityBoard.vue')['default']
    HBadge: typeof import('./resources/js/components/ui/HBadge.vue')['default']
    HButton: typeof import('./resources/js/components/ui/HButton.vue')['default']
    HCard: typeof import('./resources/js/components/ui/HCard.vue')['default']
    HCheckbox: typeof import('./resources/js/components/ui/HCheckbox.vue')['default']
    HCheckboxGroup: typeof import('./resources/js/components/ui/HCheckboxGroup.vue')['default']
    HCombobox: typeof import('./resources/js/components/ui/HCombobox.vue')['default']
    HDatePicker: typeof import('./resources/js/components/ui/HDatePicker.vue')['default']
    HDialog: typeof import('./resources/js/components/ui/HDialog.vue')['default']
    HField: typeof import('./resources/js/components/ui/HField.vue')['default']
    HFile: typeof import('./resources/js/components/ui/HFile.vue')['default']
    HIcon: typeof import('./resources/js/components/ui/HIcon.vue')['default']
    HInput: typeof import('./resources/js/components/ui/HInput.vue')['default']
    HModal: typeof import('./resources/js/components/ui/HModal.vue')['default']
    HmsShell: typeof import('./resources/js/layouts/HmsShell.vue')['default']
    HMultiSelect: typeof import('./resources/js/components/ui/HMultiSelect.vue')['default']
    HNumber: typeof import('./resources/js/components/ui/HNumber.vue')['default']
    HOffcanvas: typeof import('./resources/js/components/ui/HOffcanvas.vue')['default']
    HPage: typeof import('./resources/js/components/ui/HPage.vue')['default']
    HRadioGroup: typeof import('./resources/js/components/ui/HRadioGroup.vue')['default']
    HSegmented: typeof import('./resources/js/components/ui/HSegmented.vue')['default']
    HSelect: typeof import('./resources/js/components/ui/HSelect.vue')['default']
    HStat: typeof import('./resources/js/components/ui/HStat.vue')['default']
    HSwitch: typeof import('./resources/js/components/ui/HSwitch.vue')['default']
    HTable: typeof import('./resources/js/components/ui/HTable.vue')['default']
    HTextarea: typeof import('./resources/js/components/ui/HTextarea.vue')['default']
    HTimePicker: typeof import('./resources/js/components/ui/HTimePicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
